<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $post_id
 * @property integer $user_id
 * @property string $user_name
 * @property string $comment_body
 * @property Post $Post
 * 
 * @method integer getPostId()       Returns the current record's "post_id" value
 * @method integer getUserId()       Returns the current record's "user_id" value
 * @method string  getUserName()     Returns the current record's "user_name" value
 * @method string  getCommentBody()  Returns the current record's "comment_body" value
 * @method Post    getPost()         Returns the current record's "Post" value
 * @method Comment setPostId()       Sets the current record's "post_id" value
 * @method Comment setUserId()       Sets the current record's "user_id" value
 * @method Comment setUserName()     Sets the current record's "user_name" value
 * @method Comment setCommentBody()  Sets the current record's "comment_body" value
 * @method Comment setPost()         Sets the current record's "Post" value
 * 
 * @package    blog
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('post_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_name', 'string', 25, array(
             'type' => 'string',
             'length' => 25,
             ));
        $this->hasColumn('comment_body', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Post', array(
             'local' => 'post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}