<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/05/11 22:19:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => '19921014',
  'name' => 'doctrine',
)),);
