<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/04/15 18:17:35

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => '19921014',
  'name' => 'doctrine',
)),);
