<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/30 19:46:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
