<?php

/**
 * CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comment');
    }
    
    public static function getCommentsByPostId($id)
    {
        $q = Doctrine_Query::create()
                ->from('Comment c')
                ->select('c.comment_body, c.created_at, c.user_name')
                ->where('post_id = ?',$id)
                ->execute();
        return $q;
    }
}