<?php

/**
 * PostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Post');
    }
    
    public function getActivePosts($max)
    {
        $q=Doctrine_Query::create()
          ->from('Post p')
          ->limit($max);      
                  
        return $q->execute();
    }
    
}