# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

post:
  class: sfDoctrineRouteCollection
  options: {model: Post}

homepage:
  url:   /
  class: sfDoctrineRoute
  param: { module: post, action: index }
  options: {model: Post, type: object}

tag:
  url: /post/tag/:tag
  class: sfDoctrineRoute
  param: {module: post, action: tag }
  options: {model: Post, type: object}
  
show_post:
  url: /post/:id/:title_slug
  class: sfDoctrineRoute
  options: {model: Post, type: object }
  param: { module: post , action: show }
  requirements:
    id: \d+
    sf_method: [get,post]
    
profile_show:
  url: /profile/show/:id
  class: sfDoctrineRoute
  param: {module: userRoom, action: index }
  options: {model: sfGuardUser, type: object}

profile_edit:
  url: /profile/edit/:id
  class: sfDoctrineRoute
  param: {module: userRoom, action: edit}
  options: {model: sfGuardUser, type: object}
  requirements:
    id: \d+
    sf_method: [get,post]
    
profile_change_password:
  url: /profile/edit/:id/change_password/
  class: sfDoctrineRoute
  param: {module: userRoom, action: changePassword}
  options: {model: sfGuardUser, type: object}
    
comment_delete:
  url:     /comment/:post_id/:comment_id.:sf_format
  class:   sfDoctrineRoute
  options: { model: Comment, type: object }
  param:   { module: comment, action: delete, sf_format: html }
  requirements: { sf_method: delete }
    
  
# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }
#  
#default:
#  url:   /:module/:action/*
