Post:
  actAs: {Timestampable: ~, Taggable: ~}
  columns:
    id: { type: integer, notnull: true , primary: true}
    title: {type: string(100) , notnull: true}
    post: {type: string , notnull: true}